// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: message/message.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SignalService_StreamSignals_FullMethodName = "/message.SignalService/StreamSignals"
)

// SignalServiceClient is the client API for SignalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignalServiceClient interface {
	StreamSignals(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Signal, SignalAck], error)
}

type signalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignalServiceClient(cc grpc.ClientConnInterface) SignalServiceClient {
	return &signalServiceClient{cc}
}

func (c *signalServiceClient) StreamSignals(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Signal, SignalAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SignalService_ServiceDesc.Streams[0], SignalService_StreamSignals_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Signal, SignalAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SignalService_StreamSignalsClient = grpc.ClientStreamingClient[Signal, SignalAck]

// SignalServiceServer is the server API for SignalService service.
// All implementations must embed UnimplementedSignalServiceServer
// for forward compatibility.
type SignalServiceServer interface {
	StreamSignals(grpc.ClientStreamingServer[Signal, SignalAck]) error
	mustEmbedUnimplementedSignalServiceServer()
}

// UnimplementedSignalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignalServiceServer struct{}

func (UnimplementedSignalServiceServer) StreamSignals(grpc.ClientStreamingServer[Signal, SignalAck]) error {
	return status.Errorf(codes.Unimplemented, "method StreamSignals not implemented")
}
func (UnimplementedSignalServiceServer) mustEmbedUnimplementedSignalServiceServer() {}
func (UnimplementedSignalServiceServer) testEmbeddedByValue()                       {}

// UnsafeSignalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignalServiceServer will
// result in compilation errors.
type UnsafeSignalServiceServer interface {
	mustEmbedUnimplementedSignalServiceServer()
}

func RegisterSignalServiceServer(s grpc.ServiceRegistrar, srv SignalServiceServer) {
	// If the following call pancis, it indicates UnimplementedSignalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SignalService_ServiceDesc, srv)
}

func _SignalService_StreamSignals_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SignalServiceServer).StreamSignals(&grpc.GenericServerStream[Signal, SignalAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SignalService_StreamSignalsServer = grpc.ClientStreamingServer[Signal, SignalAck]

// SignalService_ServiceDesc is the grpc.ServiceDesc for SignalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.SignalService",
	HandlerType: (*SignalServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSignals",
			Handler:       _SignalService_StreamSignals_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "message/message.proto",
}

const (
	AggregateMerge_RequestAggMerge_FullMethodName = "/message.AggregateMerge/RequestAggMerge"
)

// AggregateMergeClient is the client API for AggregateMerge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AggregateMergeClient interface {
	RequestAggMerge(ctx context.Context, in *DenseMatrix, opts ...grpc.CallOption) (*DenseMatrix, error)
}

type aggregateMergeClient struct {
	cc grpc.ClientConnInterface
}

func NewAggregateMergeClient(cc grpc.ClientConnInterface) AggregateMergeClient {
	return &aggregateMergeClient{cc}
}

func (c *aggregateMergeClient) RequestAggMerge(ctx context.Context, in *DenseMatrix, opts ...grpc.CallOption) (*DenseMatrix, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DenseMatrix)
	err := c.cc.Invoke(ctx, AggregateMerge_RequestAggMerge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AggregateMergeServer is the server API for AggregateMerge service.
// All implementations must embed UnimplementedAggregateMergeServer
// for forward compatibility.
type AggregateMergeServer interface {
	RequestAggMerge(context.Context, *DenseMatrix) (*DenseMatrix, error)
	mustEmbedUnimplementedAggregateMergeServer()
}

// UnimplementedAggregateMergeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAggregateMergeServer struct{}

func (UnimplementedAggregateMergeServer) RequestAggMerge(context.Context, *DenseMatrix) (*DenseMatrix, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestAggMerge not implemented")
}
func (UnimplementedAggregateMergeServer) mustEmbedUnimplementedAggregateMergeServer() {}
func (UnimplementedAggregateMergeServer) testEmbeddedByValue()                        {}

// UnsafeAggregateMergeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AggregateMergeServer will
// result in compilation errors.
type UnsafeAggregateMergeServer interface {
	mustEmbedUnimplementedAggregateMergeServer()
}

func RegisterAggregateMergeServer(s grpc.ServiceRegistrar, srv AggregateMergeServer) {
	// If the following call pancis, it indicates UnimplementedAggregateMergeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AggregateMerge_ServiceDesc, srv)
}

func _AggregateMerge_RequestAggMerge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DenseMatrix)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregateMergeServer).RequestAggMerge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregateMerge_RequestAggMerge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregateMergeServer).RequestAggMerge(ctx, req.(*DenseMatrix))
	}
	return interceptor(ctx, in, info, handler)
}

// AggregateMerge_ServiceDesc is the grpc.ServiceDesc for AggregateMerge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AggregateMerge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.AggregateMerge",
	HandlerType: (*AggregateMergeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestAggMerge",
			Handler:    _AggregateMerge_RequestAggMerge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message/message.proto",
}
